name: Smart Auto VPN Update

on:
  schedule:
    - cron: '0 */2 * * *' # এটি প্রতি ২ ঘণ্টা পর পর নিজে নিজেই ব্যাকএন্ডে রান হবে
  workflow_dispatch: # এর ফলে আপনি নিজেও যেকোনো সময় ম্যানুয়ালি রান করতে পারবেন

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Premium Scraper and Ping Tester
      run: python main.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add subscription.txt
        git commit -m "Premium Nodes auto-updated with real ping and country name" || exit 0
        git push
