name: Ultimate Auto VPN System

on:
  schedule:
    - cron: '*/15 * * * *' # গিটহাবের ইন্টারনাল অটো ক্রোন সাইকেল
  push:
    branches:
      - main # কোড আপডেট বা পুশ হওয়া মাত্রই ইনস্ট্যান্ট অ্যাকশন রান হবে
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Premium Scraper and Ping Tester
      run: python main.py

    - name: Force Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add subscription.txt
        git commit -m "Professional Ultimate VPN Update [Multi-Tasking Engine]" || echo "No changes to commit"
        git push origin main
